### ISSUE TITLE
Better documentation and access of Tumblr API 

### ISSUE THREAD

**Issue by piedoom** [tumblr/tumblr_client#62]
Hi,
I have to preface this issue by stating that it is not specific to this codebase, but the Tumblr API in general.

I love using Tumblr and interfacing with the API.  I currently maintain the C# API library, write tutorials on using the Ruby library, and am working on a Rust implementation.  However, it's become more and more difficult to work with and it seems like Tumblr isn't committed to keeping the API usable.

I have a couple issues I'd like to ask about.

1: Docs and changes
===

Tumblr's V2 API library has been slowly updated with little to no documentation.  Although the changes don't seem to be breaking backwards-compatibility, they are often difficult to understand.  

For instance, take a look at the responses detailed in the [user info docs](https://www.tumblr.com/docs/en/api/v2#user-methods), and then compare those fields with an [actual request](https://gist.github.com/piedoom/625fd0e08da3f5b4e84666990da0b8ee).  As you can see, a majority of these fields are neither self-documenting nor documented in the outdated v2 docs.  

**Request:** Please revise the docs so that using the API is more enjoyable.  It stinks to think one has stable code only to [realize that the API can give sometimes unexpected results](https://github.com/piedoom/TumblrSharp/pull/14).

2: Expose currently private API endpoints
===
Although Tumblr has gained many awesome features over the years, those features have stayed largely inaccessible.  For instance, although the API endpoints for messaging/replying/or even responding to an ask privately exist, they seem to be restricted to official Tumblr clients.  I'm unsure why this is, but opening up these API methods to developers would allow for some truly awesome stuff (or even stuff vital to building a functional app, like replying to posts).   I've already seen multiple developers extract Tumblr's official client keys in order to fully utilize the restricted API which is rather unsafe for the user, so implementing this would benefit Tumblr security-wise as well.

If staff has any ideas or thoughts on these comments, please let me know!

Thanks :)

**Comment by ceyko** [comment]
@piedoom Thanks for your feedback and patience. And thank you so much for helping contribute to Tumblr’s API clients!

I agree, we have not kept a lot of our docs in sync with what is available. I’ve ticketed some work for us to review what is available publicly and make sure that all fields are documented, at least for blog and post responses so far.

However, note that we also may make some minor changes to what is available publicly, since some fields have no use externally, and will only cause additional confusion. We will not remove any currently-documented fields.

Thanks for your suggestions on making newer APIs available. We take all ideas like this into consideration for our roadmap.

If you encounter any other problems when using the API, itself, feel free to either make another issue here, or report it on the [tumblr-api mailing list](https://groups.google.com/forum/#!forum/tumblr-api) and we’ll do our best to address it.

**Comment by piedoom** [comment]
Thanks @ceyko :). I appreciate the response.

I'll close this issue and put anything further on the forums.
